-- 0001 · Tablas del inventario
--
-- Aquí viven los datos y las reglas que NUNCA se pueden romper, sin importar
-- quién escriba (la página, el bot o alguien directo en el panel):
--   · el stock y el costo no pueden ser negativos  (CHECK)
--   · no puede haber dos productos con el mismo código  (UNIQUE)
--   · el costo se guarda con dos decimales exactos  (numeric(12,2))

-- Productos -----------------------------------------------------------------
create table products (
  id           bigint generated by default as identity primary key,
  codigo       text not null unique
               check (btrim(codigo) <> '' and char_length(codigo) <= 120),
  nombre       text not null
               check (btrim(nombre) <> '' and char_length(nombre) <= 120),
  categoria    text not null
               check (btrim(categoria) <> '' and char_length(categoria) <= 120),
  stock_actual integer not null check (stock_actual >= 0),
  stock_minimo integer not null check (stock_minimo >= 0),
  costo        numeric(12,2) not null default 0 check (costo >= 0),
  -- true = "ya avisamos de este episodio de stock bajo". Evita repetir el correo.
  low_active   boolean not null default false
);

-- Movimientos (entradas y salidas) ------------------------------------------
-- Guarda el código y el nombre como TEXTO, no como referencia al producto.
-- Así el historial se conserva aunque el producto se elimine.
create table movements (
  id             bigint generated by default as identity primary key,
  product_code   text not null,
  product_name   text not null,
  tipo           text not null check (tipo in ('entrada', 'salida')),
  cantidad       integer not null check (cantidad > 0),
  stock_anterior integer not null,
  stock_nuevo    integer not null check (stock_nuevo >= 0),
  created_at     timestamptz not null default now()
);

-- El pronóstico busca las salidas recientes; este índice hace rápida esa búsqueda.
create index movements_tipo_fecha on movements (tipo, created_at);

-- Alertas -------------------------------------------------------------------
-- Cada fila es un aviso de stock bajo, con el correo ya redactado y su resultado.
create table alerts (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  items           jsonb not null,          -- productos con faltante y costos
  subject         text not null,           -- asunto del correo
  body            text not null,           -- cuerpo del correo
  status          text not null default 'pendiente'
                  check (status in ('pendiente', 'enviando', 'enviado', 'simulado', 'error')),
  error           text,
  attempts        integer not null default 0 check (attempts >= 0),
  last_attempt_at timestamptz
);

-- Ajustes -------------------------------------------------------------------
-- Pares clave/valor. Hoy solo guarda 'last_check': cuándo fue la última revisión.
create table settings (
  key   text primary key,
  value text not null
);
